spring:
    hadoop:
        fsUri: hdfs://localhost:9000
        resourceManagerHost: localhost
    yarn:
        appName: spring-boot-yarn-example
        applicationDir: /app/spring-boot-yarn-example/
        client:
            files:
              - "file:/Users/xu.zhang/IdeaProjects/spring-boot-yarn-example/my-yarn-dist/target/spring-boot-yarn-example-dist/spring-boot-yarn-example-container-1.0.0-SNAPSHOT.jar"
              - "file:/Users/xu.zhang/IdeaProjects/spring-boot-yarn-example/my-yarn-dist/target/spring-boot-yarn-example-dist/spring-boot-yarn-example-appmaster-1.0.0-SNAPSHOT.jar"
            launchcontext:
                archiveFile: spring-boot-yarn-example-appmaster-1.0.0-SNAPSHOT.jar
                arguments:
                  --my.appmaster.arg1: ${my.client.arg1:notset1}
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: spring-boot-yarn-example-container-1.0.0-SNAPSHOT.jar
                arguments:
                  --my.container.arg1: ${my.appmaster.arg1:notset2}